### ISSUE TITLE
xng-breadcrumb with different layout

### ISSUE THREAD

**Issue by capesean** [udayvunnam/xng-breadcrumb#10]
**Describe the bug**
Best described at : https://stackoverflow.com/questions/57593945/xng-breadcrumb-with-different-layout

**To Reproduce**
See: https://stackblitz.com/edit/xng-breadcrumb-65zaym?file=src%2Fapp%2Fapp.routing.module.ts

1. Load the app - notice the breadcrumb isn't displayed.
2. Click to the 'child' route. See it is displayed.
3. Click back to 'home'. See it is displayed.

2a. Click to login route.
3a. Click back to home - see it isn't displayed.

**Expected behavior**
Breadcrumb should be displayed for all home routes.

**Comment by udayvunnam** [comment]
@capesean Thanks for reporting this. When <xng-breadcrumb> is used inside a component other than root, I had to use the last parsed route config using BehaviorSubject. This is fixed, please test with the latest version of xng-breadcrumb @ 3.1.0.

I appreciate your stackblitz example to understand the bug
