### ISSUE TITLE
Angular 13: Importing BreadcrumbModule which does not have a ɵmod property

### ISSUE THREAD

**Issue by cosmin-neculau** [udayvunnam/xng-breadcrumb#103]
### Description

"Importing BreadcrumbModule which does not have a ɵmod property" when running unit tests (Jest). 

#### 🔬 Minimal Reproduction
-> Update project to Angular 13.
-> Run tests (Jest)
#### 💻Your Environment
MacOs BigSur
Node v14.15.4
NPM 6.14.11
Jest 27.3.1
Angular 13

## 🔥 Exception or Error

<pre><code>
    Importing BreadcrumbModule which does not have a ɵmod property
</code></pre>

**Comment by udayvunnam** [comment]
@cosmin-neculau we have an active PR to upgrade to Angular 13 https://github.com/udayvunnam/xng-breadcrumb/pull/102

This issue should be resolved soon once we merge the PR and release a new version

**Comment by pandamorphism** [comment]
6.8.2 works fine with Angular 13.  The issue might be with dirty .angular/cache.  Try to clean it and recompile the project.

**Comment by udayvunnam** [comment]
I have published the latest version of xng-breadcrumb-7.0.0 built with Angular CLI - 13. @cosmin-neculau please close this issue if your issue is resolved udayvunnam.github.io/xng-breadcrumb
