### ISSUE TITLE
Empty BreadcrumbModule

### ISSUE THREAD

**Issue by kyroluskamal** [udayvunnam/xng-breadcrumb#104]
### Description
Error during import BreadcrumbModule. 
I found that the BreadcrumbModule is empty
https://ibb.co/26C34rH

#### 💻Your Environment

**Angular Version:**
@angular-devkit/architect       0.1301.1
@angular-devkit/build-angular   13.1.1
@angular-devkit/core            13.1.1
@angular-devkit/schematics      13.1.1
@angular/cli                    13.1.1
@angular/flex-layout            13.0.0-beta.36
@schematics/angular             13.1.1
rxjs                            7.4.0
typescript                      4.4.4

**Comment by udayvunnam** [comment]
@kyroluskamal did you install xng-breadcrumb and import the module. Please follow the quick start https://github.com/udayvunnam/xng-breadcrumb#quickstart

**Comment by kyroluskamal** [comment]
I installed xng-breadcrumb and import the module as startup guide but it shows me an error after importation and when I opened the BreadcrumbModule, I found it empty. 

https://user-images.githubusercontent.com/37916625/145675114-fa4a361f-1d1e-4567-b5b8-70a0086445ac.mp4

I recorded a video to show you the error after installation.

**Comment by udayvunnam** [comment]
@kyroluskamal can you please provide a reproducible stack blitz. I am not able to reproduce the issue and see everyone else is able to use it.

https://udayvunnam.github.io/xng-breadcrumb

**Comment by charbel98** [comment]
I am having the same issue here, I am using angular 12, I tried to install xng-breadcrumb 6.8.2 and 6.7.0 both are giving me an empty module just like what's happening with @kyroluskamal

**Comment by udayvunnam** [comment]
I tried generating application with Nx earlier. I am able to reproduce with Angular CLI. Will push a fix soon

**Comment by charbel98** [comment]
Thank you for your fast reply !

**Comment by kyroluskamal** [comment]
Thanks for your reply @udayvunnam

**Comment by udayvunnam** [comment]
@charbel98 @kyroluskamal this is fixed in the latest version. Please try 7.0.0

**Comment by kyroluskamal** [comment]
It is working now. Thank you very much for your corporation. @udayvunnam
