### ISSUE TITLE
Since 6.8.0, breadcrumb disappears on page refresh

### ISSUE THREAD

**Issue by fgoulet** [udayvunnam/xng-breadcrumb#108]
### Description

It was working fine by injecting BreadcrumbService in the constructor of the page until I upgraded from 6.7.0 to 6.8.0

#### 🔬 Minimal Reproduction
Add a breadcrumb in the page, hit F5 to refresh the page.

#### 💻Your Environment
Windows 10

**Angular Version:**
12.1

**Comment by udayvunnam** [comment]
@fgoulet It worked fine with a demo app. Can you please provide a reproducible example to check the issue?

**Comment by fgoulet** [comment]
Hi @udayvunnam ,
I think I found why it does not work in our project. We use msal angular to handle authentication and, for some reasons, they set initialNavigation to enabledBlocking in the Router module configuration.

It was working fine until version 6.8.0. From 6.8.0 and up, if I set initialNavigation to enabledNonBlocking (the default), everything works again. But I'm not sure on the impact of this on msal angular.

Here's a repro. The breadcrumb does not appears when page load, but only when you click "change route".
https://stackblitz.com/edit/angular-xng-breadcrumbs-fku85f?file=src/app/app.routing.module.ts

**Comment by udayvunnam** [comment]
> Hi @udayvunnam , I think I found why it does not work in our project. We use msal angular to handle authentication and, for some reasons, they set initialNavigation to enabledBlocking in the Router module configuration.
> 
> It was working fine until version 6.8.0. From 6.8.0 and up, if I set initialNavigation to enabledNonBlocking (the default), everything works again. But I'm not sure on the impact of this on msal angular.
> 
> Here's a repro. The breadcrumb does not appears when page load, but only when you click "change route". [stackblitz.com/edit/angular-xng-breadcrumbs-fku85f?file=src/app/app.routing.module.ts](https://stackblitz.com/edit/angular-xng-breadcrumbs-fku85f?file=src/app/app.routing.module.ts)

Thanks, @fgoulet for identifying the issue. I have made a fix to this in xng-breadcrumb@7.1.1. Do let me know if you still face this issue.

**Comment by fgoulet** [comment]
Hi @udayvunnam , unfortunately, the issue is still present in 7.1.1. When I set intialNavigation to enabledBlocking, I loose the breadcrumb on page refresh.

**Comment by iamjustanotherrandom** [comment]
Same for me, the issue is still present in latest version

**Comment by iSpid3r** [comment]
The issue is still relevant.

xng-breadcrumb: 8.0.2
angular: 14.0.3

The "initialNavigation" parameter is needed for Server-Side Rendering.

**Comment by IlyaSurmay** [comment]
same here
xng-breadcrumb: 8.0.2
angular: 14.0.3

**Comment by marcelbarner** [comment]
I added the BreadcrumbService as constructor paramter of my AppModule and it worked. So I think the problem is that the service is initialized to late.

https://stackblitz.com/edit/angular-xng-breadcrumbs-xkivgs?file=src%2Fapp%2Fapp.routing.module.ts

**Comment by HammadKhaan** [comment]
> I added the BreadcrumbService as constructor paramter of my AppModule and it worked. So I think the problem is that the service is initialized to late.
> 
> https://stackblitz.com/edit/angular-xng-breadcrumbs-xkivgs?file=src%2Fapp%2Fapp.routing.module.ts
> 
> xng-breadcrumb: 6.8.3 angular 12.2.16

This works perfectly fine for me. Thanks :)
