### ISSUE TITLE
Cannot Install on Angular version 13. 

### ISSUE THREAD

**Issue by wwwbijay** [udayvunnam/xng-breadcrumb#112]
Cannot Install on Angular version 13.

**Comment by udayvunnam** [comment]
@wwwbijay we have it working on Angular 13. Please check - https://stackblitz.com/edit/angular-xng-breadcrumbs

check the version compatibility guide - https://udayvunnam.github.io/xng-breadcrumb/#/angular-version-compatibility.

You may need to install `xng-breadcrumb@7.0.0`
