### ISSUE TITLE
Package "xng-breadcrumb" has an incompatible peer dependency to "@angular/platform-browser-dynamic"

### ISSUE THREAD

**Issue by fgoulet** [udayvunnam/xng-breadcrumb#118]
### Description

When I try to update my project from angular 13.1.0 to 13.1.1, I got this error:

 Package "xng-breadcrumb" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires "13.1.0" (extended), would install "13.1.1")

Would it be possible to update the peer dependencies of xng-breadcrumb ?

Thanks !

**Angular Version:**

13.1.1

**Comment by marvin-belonio** [comment]
the dependency to angular should probably not be fixed to 13.1.0 but open to angular 13 so "^13.1.0"

**Comment by udayvunnam** [comment]
Whatever we specify in package.json will not end up in the final library when published.

But keeping `^` so it allows patch and minor versions is good practice. I will make this change

**Comment by udayvunnam** [comment]
@marvin-belonio and @fgoulet thanks for raising this issue, it's been fixed in `xng-breadcrumb@7.1.4`
