### ISSUE TITLE
"export 'ɵɵinject' was not found in '@angular/core'. Error for Angular 6,7 projects

### ISSUE THREAD

**Issue by udayvunnam** [udayvunnam/xng-breadcrumb#12]
**Describe the bug**
After following the install guide of XngBreadcrumb for an Angular 7 project getting error.

**To Reproduce**
1. Follow install guide
2. Import BreadcrumbModule and place <xng-breadcrumb> component

**Expected behavior**
No error should be thrown.

**Screenshots**
<img width="1264" alt="Screenshot 2019-09-28 at 10 00 35 AM" src="https://user-images.githubusercontent.com/20707504/65811516-3b435f00-e1d7-11e9-969e-07f4b9b2429a.png">

**Comment by udayvunnam** [comment]
In Angular8 defineInjectable was renamed to ɵɵdefineInjectable and defineInjectable was deprecated. This makes pre-8 libraries compatible with v8, however v8 compiled libraries will not be compatible with pre-8 consumers.

So, We should compile with Angular 7 and release it as compatible version for Angular 6 and 7.
Angular 8 compiled library will be compatible with Angular 8 + projects

**Comment by udayvunnam** [comment]
Fix verified - https://stackblitz.com/edit/angular-4roi7m

**Comment by lenichols** [comment]
@udayvunnam when will this fix be available? I am using ng7 and i am getting this error. Not sure how to fix.

**Comment by udayvunnam** [comment]
Hi @lenichols the fix is already available. The issue is fixed. Please use **xng-breadcrumb@2.1.2** for **Angular 6.x and 7.x**

Compatibility versions: https://github.com/udayvunnam/xng-breadcrumb#compatiblity-table 

The issue is because of a breaking change from @angular/core in version 8. If you ever upgrade your project to Angular 8+, use xng-breadcrumb@3.x instead
