### ISSUE TITLE
Dynamically add an item into breadcrumb

### ISSUE THREAD

**Issue by curiousThinker** [udayvunnam/xng-breadcrumb#120]
Currently the breadcrumb is generated based on route.
If my modules are on the same hierachy, is it possible to display them together in the breadcrumb ?
E.g.
{
    path: "",
    loadChildren: () => import('@modules/home/home.module').then(mod => mod.HomeModule),
    data:{ breadcrumb:'home'}
},
{
    path: "family",
    loadChildren: () => import('@modules/family/family.module').then(mod => mod.FamilyModule),
    data:{ breadcrumb:'family'}
},
{
  path: "friend",
  loadChildren: () => import('@modules/friend/friend.module').then(mod => mod.FriendModule),
  data:{ breadcrumb:'friend'}
},

For components within familyModule, the breadcrumb will be:
family / familyComponent.

But is it possible to make the breadcrumb to be something like this ?
home / family / familyComponent

On the other hand, this need to be configurable as my friendComponent breadcrumb would like to remain as:
friend / friendComponent

**Comment by udayvunnam** [comment]
not stale
