### ISSUE TITLE
RxJS peer dependency

### ISSUE THREAD

**Issue by elgurinn** [udayvunnam/xng-breadcrumb#127]
### Description

When installing the latest version 7.1.4. I get the following error (see below). 

We are using rxjs 6.x.x and Angular supports both 6 and 7 (rxjs@"^6.5.3 || ^7.4.0" from @angular/common@13.1.3). 

Is xng-breadcrumb only supporting rxjs 7.x.x if so please specify as a breaking change :) or is version 6.x.x missing from package.json ("rxjs": "^6.0.0 || ^7.0.0").

Thanks in advance.

```
npm ERR! Found: rxjs@6.5.5
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"6.5.5" from the root project
npm ERR!   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/common@13.1.3
npm ERR!   node_modules/@angular/common
npm ERR!   @angular/common@"13.1.3" from the root project
npm ERR!   peer @angular/common@">=13.0.0" from xng-breadcrumb@7.1.4
npm ERR!   node_modules/xng-breadcrumb
npm ERR!      xng-breadcrumb@"7.1.4" from the root project
npm ERR!   3 more (@angular/platform-browser-dynamic, ...)
npm ERR!   2 more (@angular/core, @angular/router)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@">=7.0.0" from xng-breadcrumb@7.1.4
npm ERR! node_modules/xng-breadcrumb
npm ERR!   xng-breadcrumb@"7.1.4" from the root project
```

**Angular Version:**
13.1.3

**Comment by udayvunnam** [comment]
Thank @elgurinn for pointing this out. Fixed in `xng-breadcrumb@7.2.0` Let me know if you further see any issue
