### ISSUE TITLE
Breadcrumb link disappears on CanDeactivate guard check when the route has a resolver. Breadcrumb loads before the resolver promise completes.

### ISSUE THREAD

**Issue by udayvunnam** [udayvunnam/xng-breadcrumb#129]
@udayvunnam  - The feature is failing in another scenario i.e. when the route has a resolver. Breadcrumb loads before the resolver promise completes. Also, I saw you have added a new filter for GuardChecksEnd in the breadcrumb service. This is breaking the earlier guard check fix which was added. Now even if "cancel" button is clicked, the breadcrumb link disappears.

 Instead of the below - line 68
.pipe(filter((event) => event instanceof GuardsCheckEnd))

replace with NavigationEnd 
.pipe(filter((event) => event instanceof NavigationEnd))

remove  "&& event.shouldActivate" from line 76

This should resolve both GuardCheck and Resolver issues.

_Originally posted by @nakash2050 in https://github.com/udayvunnam/xng-breadcrumb/discussions/111#discussioncomment-2130446_

**Comment by hugo-azevedo** [comment]
Hi, @udayvunnam , 
I too am seeing this issue.
Would it be possible to get a timeframe for this fix?
Thanks in advance for your time and attention.

**Comment by udayvunnam** [comment]
https://github.com/udayvunnam/xng-breadcrumb/discussions/111#discussioncomment-2445006

**Comment by udayvunnam** [comment]
not stale
