### ISSUE TITLE
Clicking on Breadcrumb doesn't route

### ISSUE THREAD

**Issue by lenichols** [udayvunnam/xng-breadcrumb#14]
Clicking on breadcrumb which should go to /util/r/newreport doesn't seem to map or route there. Going to the route in the url works fine. What could this be?

**Comment by lenichols** [comment]
Looking at how the navigation item is built - it looks like the router link may be incorrect. Have a look at this screenshot. @udayvunnam 

<img src="https://i.imgur.com/EwHBEsy.png" >

**Comment by udayvunnam** [comment]
Hi @lenichols, let me know if you are still facing the issue. If so, can you please provide some more details on your route and breadcrumb configuration .
