### ISSUE TITLE
Accessibility on breadcrumb's separator

### ISSUE THREAD

**Issue by kapenzo** [udayvunnam/xng-breadcrumb#140]
Hi,
first of all thank you for a greate job doing this library.
We are using it in our project which is supposed to be light accessible for the people with disabilities.

For the accissibility testing we use JAWS Screen Reader which is the most common tool for that.
The Reader has a problem with the element containing both - _arial-hidden="true" and role="separator"_
Below the line with the issue:

https://github.com/udayvunnam/xng-breadcrumb/blob/dff94d7eea3fdcc01b7e0e1796bd15672641e757/libs/xng-breadcrumb/src/lib/breadcrumb.component.html#L74

Is there a reason why the both are used?
For our case only _arria-hidden="true"_ would be the valid option - the separator should not be shown on the accessbillity API and should not contain the role property.

Should we open the pull request or could you make this change?
Thank you in advance!

**Comment by udayvunnam** [comment]
Thanks, @kapenzo for following up on this a11y issue. Please feel free to raise a PR.

Check https://udayvunnam.github.io/xng-breadcrumb/#/local-development-guide

`yarn i && yarn start` should get you up and going

**Comment by udayvunnam** [comment]
Thanks, @kapenzo, changes released with `xng-breadcrumb@8.0.2` :tada:
