### ISSUE TITLE
Hiding the breadcrumbs with one level only

### ISSUE THREAD

**Issue by SamShekhovtsov** [udayvunnam/xng-breadcrumb#169]
### Description

I would like to be able to disable showing breadcrump for one level, showing the breadcrump only if there are two or more nested levels.

for example, the following shouldn't appear:

Home

but the following should be shown:

Home -> Orders

and also this should be shown:

Home -> Orders -> Next Order

**Comment by udayvunnam** [comment]
You can already do this.

```javascript
  <xng-breadcrumb
    separator="→"
    class="your-class"
  >
    <ng-container
      *xngBreadcrumbItem="
        let breadcrumb;
        let info = info; // custom info defined for your breadcrumb
        let first = first; // boolean. Is the item first on the list 
        let count = count // count of total breadcrumbs
      "
    >
      <ng-container *ngIf="count > 1">{{ breadcrumb }}</ng-container>
    </ng-container>
  </xng-breadcrumb>
```

**Comment by SamShekhovtsov** [comment]
thanks for the suggestion, it works!
