### ISSUE TITLE
Breadcrumb text is replaced with an unexpected value

### ISSUE THREAD

**Issue by duong-do** [udayvunnam/xng-breadcrumb#17]
Hi there,

I am using version "xng-breadcrumb": "^2.1.1" for my Angular version 6 project and faced the following issue:

My route of the url has 5 level. It works fine with the route with 3 level. When an user clicks at level 4 and 5, the breadcrumb name is replaced with an unexpected value. I attached the screenshot to describe the issue below.

Hope to hear from you soon. Thanks in advance!
 
<img width="612" alt="bananen" src="https://user-images.githubusercontent.com/25991225/67252722-6a7b8200-f49e-11e9-992c-faf476a36e1e.png">

It works good at this level. When we go to the next level (click at "test"). The text "Bananen" is replaced with "Aareon" which we don't expect.

<img width="799" alt="test" src="https://user-images.githubusercontent.com/25991225/67252876-3359a080-f49f-11e9-9e9f-e231993f151a.png">

If we click at the second "Aareon", it goes back to the first image. It is correct (but not the text)

**Comment by udayvunnam** [comment]
@duong-do Can you provide sample route declaration you have for these deep routes.

**Comment by udayvunnam** [comment]
@duong-do , can you be able to share the sample route declaration and breadcrumb setup you have tried ?

**Comment by duong-do** [comment]
Thanks for your quick reply. 
I am making a sample project and will share it soon.

**Comment by duong-do** [comment]
Hi Uday,

I see how it works. At the 4th level I should define the value (name) of all previous level if needed.
Thanks

**Comment by udayvunnam** [comment]
Hey @duong-do couple of thing I have observed in your code - 

- When you want to set breadcrumb dynamically using breadcrumbService you have two options

1.  use complete path ```breadcrumbService.set('customer-list/customer-details/2', 'Aareon');```
2. name an alias for a path ```data: { breadcrumbAlias: 'customer' }``` and use setForAlias ```breadcrumbService.setForAlias('customer', 'Bananen')```

**Comment by udayvunnam** [comment]
When you have deep routes option 2 makes it easier. Refer https://github.com/udayvunnam/xng-breadcrumb#usage

**Comment by duong-do** [comment]
Dear Uday,

I am using your breadcrumb. It works wel as we expected. But when I view in the console I see the following warning.

My application is implemented on Angular 6x

**Comment by udayvunnam** [comment]
Hi @duong-do your warning message not visible. please provide image or message.

**Comment by duong-do** [comment]
Hi Uday,

We come up with another issue.

it works perfect until this step.
![breadscumb - develop page](https://user-images.githubusercontent.com/25991225/68684938-99e75100-0569-11ea-914c-29488da67b96.png)

If we click at "go to version". There is no problem. But if we "open link in new tab", then we get the following breadscrumb:

![breadscumb - version page](https://user-images.githubusercontent.com/25991225/68685234-1a0db680-056a-11ea-8c27-404a4fd7a459.png)

**Comment by udayvunnam** [comment]
Hi @duong-do, please refer to the issue https://github.com/udayvunnam/xng-breadcrumb/issues/18

The problem is where you set the `this.breadcrumbService.setForAlias('alias', 'breadcrumbLabel')`

When you move from one route to another we store all the dynamically set labels and show them in Breadcrumb.

- But when you refresh, you have to make sure the component where you have set the dynamic label is loaded into the view.
- You can move up the logic this.breadcrumbService.setForAlias() or this.breadcrumbService.set() to it's nearest parent which is always in the view no matter whichever child is rendered.

**Comment by udayvunnam** [comment]
Why warning messages are shown ?

BreadcrumbService's setForAlias(), skip(), skipForAlias() have been deprecated and removed in new release. set() method alone powers all of this features now.

Check usage https://github.com/udayvunnam/xng-breadcrumb#update-labels-dynamically and upgrade xng-breadcrumb to 4.0.0(For Angular 6)
