### ISSUE TITLE
Property '"autoGenerate"' is incompatible with index signature.

### ISSUE THREAD

**Issue by kar-21** [udayvunnam/xng-breadcrumb#171]
### Description
I am a type issue _Property '"autoGenerate"' is incompatible with index signature. Type '{ alias: "preserveQueryParams"; required: false; }' is not assignable to type 'string'_ in the  `node_modules/xng-breadcrumb/lib/breadcrumb.component.d.ts:59:90` 

#### 🔬 Minimal Reproduction Steps
- Added the `xng-breadcrumb` by executing `yarn add xng-breadcrumb`
- Added `BreadcrumbModule` to the `import` of `@NgModule` of app.model.ts
- Added `<xng-breadcrumb></xng-breadcrumb>` to the template of app.component.ts
- Started local server using `ng serve`
- Encountered this error 

```
> Error: node_modules/xng-breadcrumb/lib/breadcrumb.component.d.ts:59:90 - error TS2344: Type '{ autoGenerate: ""; preserveQueryParams: { alias: "preserveQueryParams"; required: false; }; preserveFragment: { alias: "preserveFragment"; required: false; }; class: { alias: "class"; required: false; }; anchorTarget: { ...; }; separator: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
>   Property '"preserveQueryParams"' is incompatible with index signature.
>     Type '{ alias: "preserveQueryParams"; required: false; }' is not assignable to type 'string'.
> 
> 59     static ɵcmp: i0.ɵɵComponentDeclaration<BreadcrumbComponent, "xng-breadcrumb", never, { "autoGenerate": ''; "preserveQueryParams": { "alias": "preserveQueryParams"; "required": false; }; "preserveFragment": { "alias": "preserveFragment"; "required": false; }; "class": { "alias": "class"; "required": false; }; "anchorTarget": { "alias": "anchorTarget"; "required": false; }; "separator": { "alias": "separator"; "required": false; }; }, {}, ["itemTemplate"], never, false, never>;
```

#### 💻My Environment
**Angular CLI: 15.2.0**
**xng-breadcrumb: 10.0.0**

#### 📃package.json
![image](https://github.com/udayvunnam/xng-breadcrumb/assets/51753943/b3d68f0a-8b4d-4fe3-8c90-d45eae69d32f)

## 🔥 Error
Error screenshot
![image](https://github.com/udayvunnam/xng-breadcrumb/assets/51753943/a5958a93-8283-44f0-a875-af08ba438767)

Error Code from `breadcrumb.component.d.ts`
![image](https://github.com/udayvunnam/xng-breadcrumb/assets/51753943/75dc10da-de3e-434d-be12-1c53b98338f0)

**Comment by kar-21** [comment]
I have downgraded the package to version`9.0.0`. It seems breadcrumb is working.
Not sure whether this is to do with compatibility of angular.

**Comment by udayvunnam** [comment]
Yes, this is a compatibility issue. See https://udayvunnam.github.io/xng-breadcrumb/#/angular-version-compatibility. Thanks for the update!
