### ISSUE TITLE
Customizing breadcrumb

### ISSUE THREAD

**Issue by anuj9196** [udayvunnam/xng-breadcrumb#175]
### Description
<img width="237" alt="Screenshot 2023-09-26 at 8 38 30 PM" src="https://github.com/udayvunnam/xng-breadcrumb/assets/6560085/f6e9b024-6801-4954-8c35-a3d2c2fd5d41">

In my application, I want to have a breadcrumb like the one in the screenshot, where the last element of the breadcrumb appears on a new line.

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
The breadcrumb template should be customizable so that each element style can be made custom also adding the element index or position identifier will be of help.

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by udayvunnam** [comment]
@anuj9196 please check the provided selectors https://udayvunnam.github.io/xng-breadcrumb/#/custom-styles, I guess you can achieve by changing the CSS for these selectors

**Comment by anuj9196** [comment]
Thanks @udayvunnam, it helped in getting the desired output.
