### ISSUE TITLE
Breadcrumb labels no longer working with loadChildren

### ISSUE THREAD

**Issue by MelanieW97** [udayvunnam/xng-breadcrumb#178]
### Description
I upgraded from version 10.0.0 to 10.0.1. Ever since, the defined breadcrumbs are no longer working for me.
Before:
Home

After:
Home / / [object object] >>

The routes did not change.
xng-breadcrumb seems to handle them different than before.

The documentation says you can set the breadcrumb on the child or the parent for loadChildren. That does not seem to work anymore - at least for my project.

#### 🔬 Minimal Reproduction
Define routes with loadChildren, e.g.:

![image](https://github.com/udayvunnam/xng-breadcrumb/assets/64008638/a0c44f5d-f16b-4c17-a5d1-4585368aff1f)

Then in the HomeModule:

![image](https://github.com/udayvunnam/xng-breadcrumb/assets/64008638/1a3f3b45-b3c2-4c1d-ad59-2d07fbc89340)

It was working in version 10.0.0. Maybe it's a bug or maybe you can tell me what I need to change right there in order to get it to work again.

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 16.2.8

**Comment by MelanieW97** [comment]
Hey,

I have just noticed it is no longer working on the demo website, either. No idea which version of the package you use right there, though.

Take a look.
![image](https://github.com/udayvunnam/xng-breadcrumb/assets/64008638/f10f2864-cc38-4181-9b65-a31b93b691e8)
https://xng-breadcrumb.vercel.app/mentor/add?type=add

Greetings! Have a wonderful day!

**Comment by udayvunnam** [comment]
Thanks @MelanieW97, please use 10.0.0 for now. The last merged PR https://github.com/udayvunnam/xng-breadcrumb/pull/177 may have caused this. I will check this

**Comment by liqMats** [comment]
The downgrade to 10.0.0 is a workaround for me. @udayvunnam can you please take a look at the pull request #180, which hopefully fixes this permanently? Thank you!

**Comment by udayvunnam** [comment]
@MelanieW97 @liqMats the fix is published on `xng-breadcrumb@10.0.21 Thank you!
