### ISSUE TITLE
Duplicate breadcrumbs on Angular 17

### ISSUE THREAD

**Issue by HammamBM** [udayvunnam/xng-breadcrumb#179]
### Description
I update to Angular 17 with legacy-peer-deps. It compiles and shows breadcrumbs, but they are duplicated in some sites with a last empty breadcrumb.

#### 🔬 Minimal Reproduction
Nested lazy routes shows duplicated home route and a last chevron with empty label. First and second images are the route setup: app routes and children lazy routes. Third image is the UI and the last one is the console.log of the breadcrumbs
![image](https://github.com/udayvunnam/xng-breadcrumb/assets/139541080/4bf2f02f-0a8b-4410-83ae-86a7a0d2c9bd)
![image](https://github.com/udayvunnam/xng-breadcrumb/assets/139541080/3c36e827-0347-4c5c-b8a6-9596b46273ba)
![image](https://github.com/udayvunnam/xng-breadcrumb/assets/139541080/239abbc0-a017-4575-9cf7-44e18cecf26b)
![image](https://github.com/udayvunnam/xng-breadcrumb/assets/139541080/94a91a0c-0fb9-499f-83e3-36b524f6befa)

This started to happen after update to v17.

#### 💻Your Environment

**Angular Version:**

<pre>
<code>
Angular CLI: 17.0.0
Node: 18.16.1
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1700.0
@angular-devkit/build-angular        17.0.0
@angular-devkit/core                 17.0.0
@angular-devkit/schematics           17.0.0
@angular/cdk                         17.0.0
@angular/cli                         17.0.0
@angular/material                    17.0.0
@angular/material-date-fns-adapter   17.0.0
@schematics/angular                  17.0.0
rxjs                                 7.8.1
typescript                           5.2.2
zone.js                              0.14.2
</code>
</pre>

**Comment by softworckx** [comment]
Same issue here. Just upgraded from 16 to 17.0.3:
Before:
![image](https://github.com/udayvunnam/xng-breadcrumb/assets/76793262/77555176-3373-4e17-aeda-d886d528537a)

After:
![image](https://github.com/udayvunnam/xng-breadcrumb/assets/76793262/53f1b4dc-f210-4ba3-9256-04b40ea844a1)

Any news yet?

**Comment by udayvunnam** [comment]
@HammamBM please use 10.0.0 as mentioned by @softworckx above. The last merged PR https://github.com/udayvunnam/xng-breadcrumb/pull/177 may have caused this. I will verify and provide support with Angular v17

**Comment by HammamBM** [comment]
> @HammamBM please use 10.0.0 as mentioned by @softworckx above. The last merged PR #177 may have caused this. I will verify and provide support with Angular v17

That is true. Going back to 10.0.0 works perfectly. Thank you so much. Shall I close the issue?

**Comment by softworckx** [comment]
@udayvunnam Have you already find the time to code review the open PR on this bug?

**Comment by udayvunnam** [comment]
@softworckx @HammamBM the fix is published on `xng-breadcrumb@10.0.21 Thank you!
