### ISSUE TITLE
Support for Angular 17

### ISSUE THREAD

**Issue by elgurinn** [udayvunnam/xng-breadcrumb#181]
### Description

Add support for Angular 17 see [compatibility table](https://udayvunnam.github.io/xng-breadcrumb/#/angular-version-compatibility)

**Comment by kastysik** [comment]
Hi @udayvunnam 
Will you continue to support xng-breadcrumb? If yes, when approximately can we expect Angular 17 support?
Thank you.

**Comment by frasermclean** [comment]
Any update on this? Keen to use this library in a new project.

**Comment by udayvunnam** [comment]
Hey everyone. I will spend sometime this week to upgrade this

**Comment by prokopec-simon** [comment]
Any update on this? Thanks for providing this library.

**Comment by jules-js** [comment]
hey, any update on this?

**Comment by fateeand** [comment]
When will the update be available?

**Comment by softworckx** [comment]
The upgrade would be nice, then I can finally delete this overrides-block in the package.json of my Angular v17.1 project.

```
 "overrides": {
    "xng-breadcrumb": {
      "@angular/common": "^17.1.0",
      "@angular/core": "^17.1.0",
      "@angular/router": "^17.1.0"
    }
  },
```

**Comment by udayvunnam** [comment]
Sorry for the delay guys! Will speed this up and publish an update. PR is welcome too!

**Comment by ben-mathu** [comment]
There is a dependency, `angular-in-memory-web-api`, in this library that does not support Angular 17. You will have to use npm install -f to ignore conflicting peer dependencies.

@udayvunnam Is this acceptable?

**Comment by softworckx** [comment]
Some progress in upgrading to Angular 17.x, @udayvunnam? #hoping

**Comment by prokopec-simon** [comment]
Can we count with this being updated or should we just look for other solution?

**Comment by udayvunnam** [comment]
Just now made all demo apps and breadcrumb library moved and tested with Angular 17 and standalone components. We will release this soon after some testing!

**Comment by softworckx** [comment]
@udayvunnam That's wonderful news!

**Comment by udayvunnam** [comment]
`xng-breadcrumb@11.0.0` is released with support for `Angular 17`. 

check [version compatibility guide](https://udayvunnam.github.io/xng-breadcrumb/#/angular-version-compatibility)

**Comment by softworckx** [comment]
Installed and works like a charm. I just had to change my imports.

![image](https://github.com/udayvunnam/xng-breadcrumb/assets/76793262/cd23a848-fc81-4910-83b8-f995fe8aab60)
