### ISSUE TITLE
Breadcrumb temporarily disappears during resolver data loading

### ISSUE THREAD

**Issue by l-Legacy-l** [udayvunnam/xng-breadcrumb#189]
### Description
When using the breadcrumb component in conjunction with resolver data loading, there is a noticeable flicker or disappearance of part of the breadcrumb during navigation back or when clicking on the breadcrumb link to a component loaded with a resolver.

Breadcrumb become a single label considering I'm having a two-level navigation, like just Component 1 to Component 2 navigation.

#### 🔬 Minimal Reproduction
1. Navigate to a component with breadcrumb integrated.
2. Use the breadcrumb to navigate to a the previous component or navigate back (Component should be loaded with data from resolver).

#### 💻Your Environment
**Angular Version:** 17.1.0

breadcrumb: 
```
<div class="container-breadcrumb">
    <xng-breadcrumb class="link-breadcrumb" separator=">">
      <ng-container *xngBreadcrumbItem="let breadcrumb">
        <ng-container>{{ breadcrumb | translate }}</ng-container>
      </ng-container>
    </xng-breadcrumb>
  </div>
```

Resolver:
<pre><code>
export const getThemesResolver: ResolveFn<Theme[] | null> = (): Observable<Theme[] | null> => {
  const themeService = getThemeService();
  const errorService = getErrorService();
  return themeService.getThemes<Theme>().pipe(
    tap(themes => {
      // Breadcrumb started to become a single label
    }),
    catchError(error => {
      errorService.handleResolverError(error);
      return of(null);
    })
  );
};
</code></pre>

Breadcrumb load:
<pre><code>
private buildBreadCrumb(): void {
  this.breadcrumbService.set(this.contextService.getContextForUrl() + '/:procedureId', this.decodeProcedure());
}
private decodeProcedure(): string {
  return this.theme?.getLabel(this.languageService.currentLanguageUpperCase);
}
</code></pre>

Thank you for your attention to this matter. Please let me know if you require any further information or assistance in addressing this issue.

**Comment by JhonatanMedeiros** [comment]
I have the same problem

Angular Version: 17.3.12
xng-breadcrumb: 11.0.0
