### ISSUE TITLE
Angular 17: Module '"xng-breadcrumb"' has no exported member 'BreadcrumbModule'.

### ISSUE THREAD

**Issue by charmbv** [udayvunnam/xng-breadcrumb#196]
### Description

Upgraded to version v11.0.0 of `xng-breadcrumb` and now get the following error:

    Module '"xng-breadcrumb"' has no exported member 'BreadcrumbModule'.

when I try to import the module. This is with Angular v17.3.4 and not using standalone components.

**Angular Version:**

<pre><code>
Angular CLI: 17.3.4
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.3.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-luxon-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.4
@angular-devkit/build-angular   17.3.4
@angular-devkit/core            17.3.4
@angular-devkit/schematics      17.3.4
@schematics/angular             17.3.4
ng-packagr                      17.3.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
</code></pre>

**Comment by udayvunnam** [comment]
@charmbv With Angular 17+, we use standalone components.

https://udayvunnam.github.io/xng-breadcrumb/#/quickstart?id=standalone-components

Try this -

```
import { BreadcrumbComponent, BreadcrumbItemDirective } from 'xng-breadcrumb';

@Component({
  standalone: true,
  imports: [RouterModule, BreadcrumbComponent, BreadcrumbItemDirective],
  templateUrl: './app.component.html',
  ...
})
export class AppComponent {}
```

**Comment by charmbv** [comment]
Won't work as I'm not using standalone components. This is not a requirement for using Angular 17+ so it shouldn't be a requirement for this library as well.

**Comment by TomislavMedved** [comment]
Any update on this?

**Comment by charmbv** [comment]
This is not a proper solution to the issue. I've been using `overrides` but will be looking for another solution.

**Comment by klekovkinda** [comment]
After migrating to Angular 17, I've encountered the same issue. This library is now requiring unexpected refactoring.

**Comment by diep1989** [comment]
Any update?

**Comment by JakeAi** [comment]
Instead of 
```TS
import { BreadcrumbModule } from 'xng-breadcrumb';
@NgModule({
  imports: [
    BreadcrumbModule,
  ],
```

Use 
```TS
import { BreadcrumbComponent, BreadcrumbItemDirective,  } from 'xng-breadcrumb';
@NgModule({
  imports: [
    BreadcrumbComponent, BreadcrumbItemDirective,
  ],
```

**Comment by bahnhub** [comment]
> Instead of
> 
> ```ts
> import { BreadcrumbModule } from 'xng-breadcrumb';
> @NgModule({
>   imports: [
>     BreadcrumbModule,
>   ],
> ```
> 
> Use
> 
> ```ts
> import { BreadcrumbComponent, BreadcrumbItemDirective } from 'xng-breadcrumb';
> @NgModule({
>   imports: [
>     BreadcrumbComponent, BreadcrumbItemDirective,
>   ],
> ```

The provided solution from JakeAi worked for me
