### ISSUE TITLE
Angular 18 

### ISSUE THREAD

**Issue by ehsan-shahrestani** [udayvunnam/xng-breadcrumb#202]
### Description
when i run npm install xng-breadcrumb i get error  version

#### 💻Your Environment

**Angular Version:**
"^18.0.5"

<pre><code>

## 🔥 Exception or Error

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: patok-resellers-frontend@0.0.0
npm error Found: @angular/common@18.0.6
npm error node_modules/@angular/common
npm error   @angular/common@"^18.0.5" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @angular/common@"^17.2.0" from xng-breadcrumb@11.0.0
npm error node_modules/xng-breadcrumb
npm error   xng-breadcrumb@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/ehsan/.npm/_logs/2024-07-05T07_43_37_831Z-eresolve-report.txt

npm error A complete log of this run can be found in: /home/ehsan/.npm/_logs/2024-07-05T07_43_37_831Z-debug-0.log

<pre><code>

</code></pre>

**Comment by KristofGilis** [comment]
#204

**Comment by SalvoDiblasi** [comment]
+1

**Comment by apappas1129** [comment]
You can install it with `--legacy-peer-deps` but note that you may experience the same issue as [this](https://github.com/udayvunnam/xng-breadcrumb/issues/198#issuecomment-2190723943).
