### ISSUE TITLE
Defining breadcrump in child not working with empty route

### ISSUE THREAD

**Issue by Benny739** [udayvunnam/xng-breadcrumb#25]
Hi,

setting breadcrumb in a lazy loaded child module with empty route is not working.

My parent Route:
        {
          path: 'courses',
          data: {
            breadcrumb: 'Deine Kurse'
          },
          loadChildren: () => import('./courses/courses.module').then(mod => mod.CoursesModule)
        },

Route in the child module:
  {
    path: '',
    pathMatch: 'full',
    component: CoursesOverviewComponent,
    data: {
      breadcrumb: 'Deine Kurse Neu'
    }
  },

This ends in no custom breadcrumb data at all. If I remove the breadcrumb from the child, the value from the parent is shown. If the route from the child is not empty, everything is working fine. No data on the parent also makes no difference.

Regards
Benny

**Comment by udayvunnam** [comment]
Hi Benny, 

It is by design, we have made this pattern. Breadcrumbs can be shown for routes that can be differentiated by the path. 

In your example, you would want to choose breadcrumb for path "/courses" on either parent on children. If it's defined at many places for the same path then the deepest child takes priority.

Please check https://github.com/udayvunnam/xng-breadcrumb#where-to-define-breadcrumbs-if-routes-path-have-same-route-specificity

**Comment by udayvunnam** [comment]
@Benny739

**Comment by patogalla** [comment]
It happens the same to me in the last version.
I had to add, twice "breadcrumb" key.
For instance:

{
    path: '',
    data: { breadcrumb: {breadcrumb: 'Organizations'} },
    component: ...
  },

**Comment by udayvunnam** [comment]
Hi, @patogalla! Can you provide the Angular and xng-breadcrumb version you have faced this issue on?

Also, I see that you are defining it wrongly.

Use one of the below patterns - 
- just label: https://github.com/udayvunnam/xng-breadcrumb#breadcrumb-as-a-string
- label, icon, additional info for advanced usage - https://github.com/udayvunnam/xng-breadcrumb#breadcrumb-as-an-object

**Comment by patogalla** [comment]
Hi @udayvunnam , thanks for the response. 
Here are the versions:
Angular:
xng-breadcrumb:

Regarding the way i defined in my project, is after debuging your code, found that if i put the breadcrumb object inside another breadcrumb object it worked.
I think it has to be with nested routes, and the way it handle it.
I have like a 3 or 4 level depth routing.

Any thing you need, just ask me, i'd be glad to help.

**Comment by udayvunnam** [comment]
Hi @patogalla can you use the latest version where a couple of bugs are addressed.
https://github.com/udayvunnam/xng-breadcrumb#angular-version-compatibility

**Comment by udayvunnam** [comment]
@patogalla is that working upgrading to the latest
