### ISSUE TITLE
The set method does not immediately change the breadcrumbs.

### ISSUE THREAD

**Issue by yakupov112** [udayvunnam/xng-breadcrumb#26]
I get api data and try to dynamically change breadcrumbs. But the changes are applied only after the route or its parameters change
![1](https://user-images.githubusercontent.com/22240080/72715240-2bce9400-3b81-11ea-8af1-c030fbe837ab.gif)

**Comment by yakupov112** [comment]
angular - 6 version
xng-breadcrumb - 4.0.0

**Comment by udayvunnam** [comment]
@yakupov112 this is strange. Can you provide code sample of in which component are you updating the breadcrumb dynamically. Also, are updating it via any lifecycle methods

**Comment by yakupov112** [comment]
Hi, @udayvunnam
> Can you provide code sample of this?

OnInit method:

`  ngOnInit() {
    forkJoin([
      this.subscribeToRoute(),
      this.subscribeToUser(),
      this.getCategory()
    ])
      .subscribe();
  }`

getCategory method:

`  private getCategory() {
    return this.categoryService.getCategory().pipe(
      tap((data) => {
        this.breadcrumbService.set('families/:id', data.categoryName);
      }),
    );
  }`

> Which component are you using to update the breadcrumb dynamically?

I try to do this in a component in which I get data on the necessary header for the crumbs. That is, a category component

> Also, are you updating it in any of the lifecycle methods?

I call the get data method in the OnInit method. After that, I call the dynamically change the crumbs method. You can see it in the example above.

![1](https://user-images.githubusercontent.com/22240080/72779991-938ee880-3c2e-11ea-9d1f-aee3afa1846a.gif)
On the gif, you can see that the necessary crumb is still passed to breadcrumbService, but it does not apply

**Comment by scarfex** [comment]
Hello, i've been having this same issue, any progress on a solution?

**Comment by udayvunnam** [comment]
In progress - @scarfex. Will release the fix in a week

**Comment by udayvunnam** [comment]
@scarfex @yakupov112 - This is fixed on the latest version of **xng-breadcrumb**. Either upgrade to 4.1.0 or 5.1.0 depending on your Angular version. Thanks for reporting this.

Check the version compatibility - https://github.com/udayvunnam/xng-breadcrumb#angular-version-compatibility
