### ISSUE TITLE
Parameterized Routes not working 

### ISSUE THREAD

**Issue by shray7** [udayvunnam/xng-breadcrumb#34]
**Describe the bug**
Whenever using breadcrumbs, and you have a parametrized route, breadcrumb doesnt _save_ the parameters so you can navigate back

**To Reproduce**
https://stackblitz.com/edit/angular-9-starter-material-hhqmpb

1.Navigate to stackblitz.
2. Click on 'Catalog' link (first bread crumb will appear)
3. Click on any movies link (2nd bread crumb will appear)
4. Click 'Catalog' Breadcrumb
5. Notice URL does not contain proper id parameter

**Expected behavior**
Routing parameters should be saved when routing back on breadcrumbs

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: Latest enough

**Comment by mahmoudparandeh** [comment]
@shray7  that is exactly what i told on previous issue. thanks for reproduce.

**Comment by shray7** [comment]
I've decided to abandon this package, and instead go for [this package](https://www.npmjs.com/package/ng7-mat-breadcrumb) instead. I was able accomplish what I wanted

**Comment by udayvunnam** [comment]
@shray7 sorry to see you go. I will try what can be done for this issue. Thanks!

**Comment by udayvunnam** [comment]
@shray7 @mahmoudparandeh This issue has been fixed with latest release xng-breadcrumb@6.0.0

**Comment by mahmoudparandeh** [comment]
@udayvunnam well-done. i will update my apps based on new update. thanks
