### ISSUE TITLE
QueryParams being assigned to incorrect routes

### ISSUE THREAD

**Issue by mrum-cuscal** [udayvunnam/xng-breadcrumb#36]
**Describe the bug**
I have some routes which have query params. e.g.
route1: statements (no query params)
route2: statement/:statementId?key=value
route3: statement/:statementId/:otherroute?key=value&key2=value2

When I navigate to route3 I am finding that my route1 and route2 are getting assinged the query params from route3 

I think the issue is in the resolveQueryParam method. It seems to be assigning the queryParams to the all the routes (not just the route that requires them)

**Comment by udayvunnam** [comment]
@mrum-cuscal Thanks for reporting this bug. A PR fix is always welcome. If not, I will try fixing this weekend.

**Comment by jeejeeu** [comment]
Thanks, logged in with a work account previously. I have isolated the issue to the resolveQueryParam method but cannot quite understand how to fix it correctly. Any help would be greatly appreciated.

**Comment by udayvunnam** [comment]
@mrum-cuscal @jeejeeu This issue has been fixed with latest release xng-breadcrumb@6.0.0

**Comment by jeejeeu** [comment]
Thanks for the fix.
