### ISSUE TITLE
DIsable Fragment preservation

### ISSUE THREAD

**Issue by Benny739** [udayvunnam/xng-breadcrumb#38]
Hi,

is it possible to disable the preservation of the fragment?

Regards
Benny

**Comment by udayvunnam** [comment]
@Benny739 Yes! I will add this ability with the next minor release in a few days. 

May I know your use case of where you want to avoid fragment? With the browser back button the history API preserves fragment, the same is considered for the breadcrumbs navigation.

**Comment by Benny739** [comment]
@udayvunnam Thx :)
The fragment makes our page scroll to an element. At least for me, when I click on a breadcrumb I expect to see the top of the page. When you go back it is standard, that the browser remembers where u where. But with a breadcrumb, I would like to stay at the top of the page. 
The navigation path is pretty complex in our app, so clicking on the same element in the breadcrumb leads sometimes to scroll (because we had a fragment) and sometimes not to scroll. So it feels a little inconsistent. I think an element should always do the same thing, otherwise it's hard for the user to remember when it does what.

**Comment by udayvunnam** [comment]
@Benny739 https://github.com/udayvunnam/xng-breadcrumb/releases/tag/v6.1.0 provides this feature. upgrade xng-breadcrumb version to 6.1.0
