### ISSUE TITLE
The demo page is down

### ISSUE THREAD

**Issue by DannyFeliz** [udayvunnam/xng-breadcrumb#39]
Just letting you know that the demo page is not working.
![image](https://user-images.githubusercontent.com/5460365/90174450-fd5e1380-dd73-11ea-902c-fe12d8f6918c.png)

**Comment by udayvunnam** [comment]
Thanks for reporting @DannyFeliz. This is to do with netlify changing from .com to .app. I will update the references.

For now please use https://xng-breadcrumb.netlify.app/dashboard

**Comment by DannyFeliz** [comment]
@udayvunnam still down ![Screenshot_20200813-215622.jpg](https://user-images.githubusercontent.com/5460365/90203878-e0473600-ddaf-11ea-9729-4638d2a4784a.jpg)

**Comment by udayvunnam** [comment]
Ahh I see. It's working with client side navigation. I will correct the netlify reroutes. Use https://xng-breadcrumb.netlify.app and then client side navigation

**Comment by DannyFeliz** [comment]
I guess this is done.

BTW, I love this package, I was doing my own breadcrumb but it comes with its own difficulties and with this, I was able to solve all my problems.
