### ISSUE TITLE
Child breadcrumb with empty path is ignored and replaces parent

### ISSUE THREAD

**Issue by chad-smith** [udayvunnam/xng-breadcrumb#44]
I have found some odd behaviour when defining empty paths, it's quite fiddly to explain in text, so I have altered the demo site to reproduce my findings.

If you apply the changes in https://github.com/chad-smith/xng-breadcrumb/compare/master...demo-data-bug you will find that neither of the breadcrumbs being set are used.

After a bit of poking around, I found the following:
1. Removing the root `data: { breadcrumb: ...}` makes no difference
2. Removing the module `data: { breadcrumb: ...}` resolves the issue
3. Removing the breadcrumb label but keeping the `data: {}`_ in the module causes the issue!

Scenario 3 is why the project I'm using breadcrumbs on has been seeing the problem (we use the data attributes frequently for permissions).

NB: If you deviate from an empty path, you will see both breadcrumbs as expected.

I thought this might be related to #25 because using the 'hack' that was described there also seems to work.

**Comment by chad-smith** [comment]
To make this a little more visual, with the code changes referenced, I see this:

![image](https://user-images.githubusercontent.com/1563668/92239830-88ce4e80-eeb3-11ea-916b-45aa07fc40ea.png)

And I am expecting to see this:

![image](https://user-images.githubusercontent.com/1563668/92240185-1ca01a80-eeb4-11ea-8e32-898706cb11af.png)

Whilst prepping those screenshots, I noticed that whilst I could get it to display `Mentee (Root)`, I couldn't get it to display `Mentee (Module)` (the above screenshot is faked).

Either value would probably work for us, but it seems logical that both should (with the child taking precedence)

**Comment by chad-smith** [comment]
Also, sorry for keep finding problems 😄 

If it's any consolation, I'm invested in flushing them all out because it's a library I intend to use in multiple projects and recommend to others 👍

**Comment by udayvunnam** [comment]
@chad-smith I really appreciate you for finding and reporting these subtle bugs - I have fixed this and also [covered it in a test so that it won't break again](https://github.com/udayvunnam/xng-breadcrumb/blob/f6c9214af953c765f4beb3a5bfe47546f028a956/apps/breadcrumb-demo-e2e/src/integration/default.spec.ts#L58). Fix available with version 6.2.0 🎉

https://github.com/udayvunnam/xng-breadcrumb/releases/tag/v6.2.0

**Comment by udayvunnam** [comment]
@nativeforest your issue is fixed with xng-breadcrumb@6.8.1
