### ISSUE TITLE
Node module error occurring

### ISSUE THREAD

**Issue by velu-dev** [udayvunnam/xng-breadcrumb#46]
I have using angular version 8+. and installed xng-breadcrumb version 6+. But I got an error like this. how to I solve it?

`ERROR in node_modules/xng-breadcrumb/lib/breadcrumb.component.d.ts:48:9 - error TS1086: An accessor cannot be declared in an ambient context.

     set separator(value: string | TemplateRef<void>);
           ~~~~~~~~~
node_modules/xng-breadcrumb/lib/breadcrumb.component.d.ts:49:9 - error TS1086: An accessor cannot be declared in an ambient context.

   get separator(): string | TemplateRef<void>;
           ~~~~~~~~~
`

**Comment by udayvunnam** [comment]
@velu-dev can you provide a minimal reproducible example with https://stackblitz.com/

**Comment by udayvunnam** [comment]
closing this as there is no update here!

**Comment by udayvunnam** [comment]
closing this as there is no update here!
