### ISSUE TITLE
Separator showing before first item

### ISSUE THREAD

**Issue by paulmhan** [udayvunnam/xng-breadcrumb#55]
![Screen Shot 2020-11-13 at 4 20 10 PM](https://user-images.githubusercontent.com/58451541/99132712-1d4be000-25cc-11eb-8a80-e06ae8ca046f.png)

I am trying to get rid of the first separator but I am now convinced this is a bug. 

![Screen Shot 2020-11-13 at 4 21 18 PM](https://user-images.githubusercontent.com/58451541/99132749-453b4380-25cc-11eb-9f68-5ba66cc8305e.png)

I changed the background color of the breadcrumb link to make sure there was not a blank item before the first separator.

Can I get some help on how to fix this?

**Comment by udayvunnam** [comment]
@paulmhan This is fixed in the latest version 6.3.3. Thanks for reporting the issue.

**Comment by paulmhan** [comment]
Thank you so much!

**Comment by paulmhan** [comment]
So I just updated the package and the separator is still showing

**Comment by paulmhan** [comment]
Is there also a way to get rid of the way the active link is elevated?

**Comment by udayvunnam** [comment]
@paulmhan This has been overlooked for another fix. The issue is fixed with **version 6.3.4** and also a test case is added to validate this.
