### ISSUE TITLE
How to get rid of elevated active link

### ISSUE THREAD

**Issue by paulmhan** [udayvunnam/xng-breadcrumb#57]
The active link in the breadcrumbs is always elevated. Is this a bug? I cannot find it in the documentation and the live demo has all breadcrumbs in the same level. Please let me know how to resolve.

![Screen Shot 2020-11-16 at 12 22 44 PM](https://user-images.githubusercontent.com/58451541/99303964-9767a900-2806-11eb-9339-af0c48c7c241.png)

**Comment by udayvunnam** [comment]
@paulmhan One reason could be that, you may have app-level <li> styles that are interfering with breadcrumb styles. If that's not the case provide a minimal reproducible example with https://stackblitz.com/edit/angular-xng-breadcrumbs

**Comment by paulmhan** [comment]
Sounds good, thank you!
