### ISSUE TITLE
Change breadcrumbs manually 

### ISSUE THREAD

**Issue by PHPadawan** [udayvunnam/xng-breadcrumb#59]
Hello,

is there a way to change/manipulate the breadcrumbs?
My router file looks like this: 

path: 'servers', component: ServerListComponent, data: { breadcrumb: 'Servers' }},  -> **App / Servers**
path: 'server/:id', component: ServerDetailComponent, data: { breadcrumb: { alias: 'serverName' }}}, -> **App / Webserver 1**

Since servers doesn't have a router-outlet for server/:id it cant be a child route. But I want the breadcrumbs like 
**App / Servers / Webserver 1**. Is this possible to archiv?

Many greetings

**Comment by vitaliy-patsay** [comment]
Hi, intereseted in the same use case

**Comment by udayvunnam** [comment]
@PHPadawan @vitaliy-patsay 

- Inserting breadcrumbs manually between autogenerated breadcrumbs can be implemented, and that can be picked as a major enhancement
- However, I have a solution for you! Can you try with the route configuration as below. This should work
```javascript
      {
        path: 'servers',
        data: { breadcrumb: 'Servers' },
        children: [
          {
            path: '',
            component: ServerListComponent, 
          },
          {
            path: ':id',
            component: ServerDetailComponent,
            data: { breadcrumb: { alias: 'serverName' }}
          },
        ],
      }
```

**Comment by udayvunnam** [comment]
@PHPadawan please close the issue if above solution is feasible to you

**Comment by PHPadawan** [comment]
I have not thought of this simple solution. Thank you!
