### ISSUE TITLE
Breadcrumb not refreshed when calling `breadcrumbService.set()`

### ISSUE THREAD

**Issue by gilsdav** [udayvunnam/xng-breadcrumb#74]
### Description

I can see your breadcrumb is not observable from the store to the html.

https://github.com/udayvunnam/xng-breadcrumb/blob/f63924f7f844fc6d512c4ca4ff10e75b0eab4dc0/libs/xng-breadcrumb/src/lib/breadcrumb.component.ts#L92

This is not compatible with full of partial "onPush" angular apps.

`this.breadcrumbs` needs to be an observable (no subscribe in ngOnInit) and use the pipe `async` into the HTML.

#### 💻Your Environment

Angular: 11.2.2
Breadcrumb: 6.6.0

**Comment by udayvunnam** [comment]
Thanks for raising the issue @gilsdav!

🎉 The fix is included in version 6.6.1 🎉

The release is available on - https://www.npmjs.com/package/xng-breadcrumb/v/6.6.1
