### ISSUE TITLE
Styling in .scss isn't taking effect for .xng-breadcrumb-trail color

### ISSUE THREAD

**Issue by chmorgan** [udayvunnam/xng-breadcrumb#77]
## 🐞 Bug report
Trying to use:

::ng-deep .xng-breadcrumb-trail {
    color: white;
    background-color: red;
}

in my app.component.scss file

to change the trail text to be white.

### Description

Background color goes red but text color is stuck black.

#### 💻Your Environment

**Angular Version:**
11.2.2

<pre><code>

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.1
Node: 12.18.2
OS: linux x64

Angular: 11.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.1
@angular-devkit/build-angular   0.1102.1
@angular-devkit/core            11.2.1
@angular-devkit/schematics      11.2.1
@angular/cdk                    11.2.1
@angular/cli                    11.2.1
@angular/material               11.2.1
@schematics/angular             11.2.1
@schematics/update              0.1102.1
rxjs                            6.6.3
typescript                      4.1.5

## 🔥 Exception or Error

<pre><code>

</code></pre>

**Comment by chmorgan** [comment]
It also seems to not take effect with ::ng-deep .xng-breadcrumb-root or item when I'm at the top level page.

**Comment by udayvunnam** [comment]
Not stale

**Comment by udayvunnam** [comment]
@chmorgan can you try styling this way - https://github.com/udayvunnam/xng-breadcrumb/blob/0e15963fe928d6809ed8ca4b79f8d6a5261e5a9e/apps/breadcrumb-demo/src/styles.scss#L61

**Comment by udayvunnam** [comment]
Here's is the documentation for customizing styles https://github.com/udayvunnam/xng-breadcrumb/blob/main/docs/advanced-patterns.md#custom-breadcrumb-styles
