### ISSUE TITLE
Can not add xng-breadcrumb to my project

### ISSUE THREAD

**Issue by DirkStorck** [udayvunnam/xng-breadcrumb#78]
### Description
After I have used the command 
"npm i xng-breadcrumb"
I get the an error on BreadcrumbModule

#### 💻Your Environment

**Angular Version:**

<pre><code>
PS I:\workspaces-angular-ts\angular-tour-of-heroes\angular-tour-of-heroes-pt5> npm version
{
  'angular.io-example': '0.0.0',
  npm: '6.14.8',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.15.0',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.17',
  zlib: '1.2.11'
}

Angular CLI: 11.2.4
Node: 14.15.0
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------  
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.2.4
@angular/cli                    11.2.4
@schematics/angular             11.2.4
@schematics/update              0.1102.4
rxjs                            6.6.6
typescript                      4.0.7
## 🔥 Exception or Error
</code></pre>

<pre><code>
"class BreadcrumbModule
Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (xng-breadcrumb) which declares BreadcrumbModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.(-996002)"
</code></pre>

**Comment by udayvunnam** [comment]
@DirkStorck see the usage at https://github.com/udayvunnam/xng-breadcrumb#quickstart. 

Did you forgot to import BreadcrumbModule in the root of your App.

```javascript
import {BreadcrumbModule} from 'xng-breadcrumb';
@NgModule({
  ...
  imports: [BreadcrumbModule],
  ...
})
export class AppModule { }
```
