### ISSUE TITLE
make the breadcrumb's link middle or right mouse clickable to open it in new tab

### ISSUE THREAD

**Issue by udayvunnam** [udayvunnam/xng-breadcrumb#81]
### Description

Currently, if you try to click a link with the middle mouse button, nothing happens.

![image](https://user-images.githubusercontent.com/37147299/113578545-3e68a800-9623-11eb-8ef7-1ab8d41f098e.png)

_Originally posted by @borisBelloc in https://github.com/udayvunnam/xng-breadcrumb/discussions/80_

### Describe the solution you'd like

**I'm not sure** but I think I'm looking to make the link `[href]` rather than using `[routerlink]`

### Describe alternatives you've considered

NA

**Comment by udayvunnam** [comment]
@borisBelloc I am trying to add this behavior. Do you wish this as a global behaviour or per-route behaviour

**Comment by borisBelloc** [comment]
Hello, 
I hope I understand your question, 
I would use it as global. I always make my links clickable with the middle button (openable in new tab) but if it's not too much work, per-route behavior would allow every user of  xng-breadcrumb to choose how it works on their app (?)

**Comment by udayvunnam** [comment]
@borisBelloc This feature is added with version `6.7.0` 🧨

- You can now click `cmd + click to open the link in the new tab by default
- If you wish to open all breadcrumb links in a new tab you can do so by https://github.com/udayvunnam/xng-breadcrumb/blob/main/docs/advanced-patterns.md#open-breadcrumb-link-in-new-tab
