### ISSUE TITLE
Couldn't set label from component when [autoGenerate]="false"

### ISSUE THREAD

**Issue by misterSerg** [udayvunnam/xng-breadcrumb#84]
### Description

When I set a label with service for path chunk that was already autogenerated, it remains autogenerated and is filtered by [autoGenerate]="false" property.

Service BreadcrumbService creates BreadcrumbDefinition with isAutoGeneratedLabel = true;
It's still autogenerated after we set label within a component.

I think we should reset isAutoGeneratedLabel if it is set by user in any time

here: https://github.com/udayvunnam/xng-breadcrumb/blob/212571fd2158fdd2baafd1b9d87e7e51f4488dd6/libs/xng-breadcrumb/src/lib/breadcrumb.service.ts#L336

#### 🔬 Minimal Reproduction

1) I've disabled "autoGenerate" option to manually control breadcrumb labels. 

`<xng-breadcrumb [autoGenerate]="false" [preserveFragment]="false"></xng-breadcrumb>`

2) My route config have not label for path chunk
<pre><code>
{
  path: ':id',
  data: {
    breadcrumb: {
      alias: BreadcrumbAlias.wallet,
    } as BreadcrumbObject,
  },
</code></pre>

3) But I've set a label in the component:
<pre><code>
ngOnInit(): void {
    this.breadcrumbService.set(`@${BreadcrumbAlias.account}`, { skip: false });
    this.breadcrumbService.set(`@${BreadcrumbAlias.wallet}`, this,wallet.title);
}
</code></pre>

Result: My breadcrumb is filtered in BreadcrumbComponent. So it's not visible for user

#### 💻Your Environment

**Angular Version:**

<pre><code>
Angular CLI: 11.2.2
Node: 14.16.1
OS: win32 x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes
</pre></code>

**Ngx-breadcrumb Version**

xng-breadcrumb: 6.6.1

**Comment by udayvunnam** [comment]
Hi, @misterSerg thanks for reporting this bug. I will check this. You can also raise a PR with the fix if you are aware of the fix.

**Comment by udayvunnam** [comment]
not stale

**Comment by udayvunnam** [comment]
Not stale

**Comment by udayvunnam** [comment]
@misterSerg this issue is fixed with `xng-breadcrumb@6.8.2`
