### ISSUE TITLE
CSS and separator not working

### ISSUE THREAD

**Issue by MiteshGohil7** [udayvunnam/xng-breadcrumb#86]
## 🐞 Bug report
I was trying to use this component but it seems CSS not working for my project 
### Description
I have tried to use it like below in my app.component 
![image](https://user-images.githubusercontent.com/89067746/130051716-84b706f6-9cca-40bf-b0a4-6efd2ddd977b.png)

but when I run it shows like below
![image](https://user-images.githubusercontent.com/89067746/130051989-c3d758ee-d5f6-4c19-9df5-45e5af77203b.png)

as you can see its plain breadcrumbs without any link also separator is not working as mentioned in the code
I have injected a module in my app module like below

![image](https://user-images.githubusercontent.com/89067746/130052185-2915ea5e-2555-4384-b2e1-d0510b2b2e69.png)

**Angular Version:**
~12.0.1

Note: I am not using any angular material is that can be the cause?
I am using the IONIC framework and components

**Comment by MiteshGohil7** [comment]
okay, I found out that I have to use your custom CSS to have the same CSS and there was some routing issue that fixed the other issues.
But now in my case, I have 2 siblings' components that I want to show as a child component so, is there any way to do that and if not can I add custom breadcrumbs in the data?

**Comment by udayvunnam** [comment]
@MiteshGohil7 please check the styles guide for customization https://github.com/udayvunnam/xng-breadcrumb/blob/main/docs/advanced-patterns.md#custom-breadcrumb-styles

**Comment by udayvunnam** [comment]
you can do that easily - please refer to demo app in https://github.com/udayvunnam/xng-breadcrumb/blob/main/apps/breadcrumb-demo/src/app/mentor/mentor-routing.module.ts
