### ISSUE TITLE
multiple routing files

### ISSUE THREAD

**Issue by Hesesses** [udayvunnam/xng-breadcrumb#9]
Hello,

I have `layout-routing.module.ts` which has:
```
const routes: Routes = [
  {
    path: '', component: LayoutComponent, data: {breadcrumb: 'my app name'}, children: [
      {path: 'home', loadChildren: '../home/home.module#HomeModule'},
      {path: 'users', loadChildren: '../users/users.module#UsersModule'},
      {path: 'login', loadChildren: '../login/login.module#LoginModule'},
      { path: '**', redirectTo: '/home', }
    ],
  },
];
```
and then `users-routing.module.ts`
```
const routes: Routes = [
  {path: '', pathMatch: 'full', component: UsersComponent, data: {breadcrumb: 'Users'}},
  {path: 'add', component: AddUserComponent, data: { breadcrumb: 'Add new'}},
  { path: ':userId', data: {breadcrumbAlias: 'userFullname'}, children: [
      {path: '', component: ShowUserComponent},
      {path: 'edit', component: EditUserComponent, data: {breadcrumb: 'edit'}}
    ]}
];
```

What I would like to have is to have my app name always first part of the breadcrumb, is this possible this way?

**Comment by udayvunnam** [comment]
This should work. Do you see it not working @Hesesses?

**Comment by Hesesses** [comment]
Yes, for me it shows `users / add new` for example instead of `app name / users / add new`

**Comment by Hesesses** [comment]
Any updates on this? 🙏

**Comment by udayvunnam** [comment]
@Hesesses I will look into it, this weekend.

**Comment by udayvunnam** [comment]
Hi @Hesesses 

Declaration with children and parent relationship - breadcrumb data can be decalred either on parent or on child with empty path. The latter takes precedence.

With component children
// declaring breadcrumb data on component parent
  {
    path: ':userId',
    data: { breadcrumb: 'My User declared on parent' },
    children: [
      { path: '', component: ShowUserComponent }
    ]
  }
// declaring breadcrumb data on component child with empty
  {
    path: ':userId',
    children: [
      { path: '', component: ShowUserComponent, data: { breadcrumb: 'My User declared on empty child' }
    ]
  }
With Module children
// declaring breadcrumb data on module
  { path: 'home', loadChildren: './home/home.module#HomeModule', data: { breadcrumb: 'Dashboard' } }

// declaring breadcrumb data on module child with empty
  { path: 'home', loadChildren: './home/home.module#HomeModule' },
  { path: '', pathMatch: 'full', component: HomeComponent, data: { breadcrumb: 'Dashboard' } }

**Comment by udayvunnam** [comment]
Hi @Hesesses please check - https://github.com/udayvunnam/xng-breadcrumb#usage

**Comment by udayvunnam** [comment]
I have tested your use case and also added a demo and it seems to work. please check https://github.com/udayvunnam/xng-breadcrumb/blob/master/projects/demo/src/app/app-routing.module.ts

**Comment by udayvunnam** [comment]
if you still face any issue please provide a https://stackblitz.com with example
