### ISSUE TITLE
A way to be able to say if you want to translate the text or not.

### ISSUE THREAD

**Issue by BorjaLagarejo** [udayvunnam/xng-breadcrumb#90]
### Description

A way to be able to say if you want to translate the text or not.

For example, from a customer list screen, to data of the selected customer.

Customers > (Customer's name) > personal information

To change the name of the client I am using "alias", but I can't find a way to detect in html if this data or another data like "translate" is coming.

### Describe the solution you'd like

For example, when passing "translate: false" do not translate the text.

```ts
const route: Route[] = [
    {
        path: '',
        component: ClientesListaComponent,
        data: {
            breadcrumb: {
                skip: false,
                label: 'TITLE_CLIENTS',
                translate: true
            },
        },
    },
    {
        path: ':id',
        component: ClienteComponent,
        data: {
            breadcrumb: {
                skip: false,
                label: 'TITLE_CLIENT',
                alias: 'aliasCliente',
                translate: false
            },
        },
```

```html
<xng-breadcrumb [separator]="iconTemplate" class="hidden sm:flex flex-wrap items-center font-medium">
    <ng-container *xngBreadcrumbItem="let breadcrumb; let translate;">
        <ng-container *ngIf="translate">{{ breadcrumb | transloco | titlecase }}</ng-container>
        <ng-container *ngIf="!translate">{{ breadcrumb | titlecase }}</ng-container>
    </ng-container>
</xng-breadcrumb>
<ng-template #iconTemplate>
    <mat-icon class="icon-size-5 text-secondary" [svgIcon]="'heroicons_solid:chevron-right'"></mat-icon>
</ng-template>
```

### Describe alternatives you've considered

For the time being, no

**Comment by udayvunnam** [comment]
Hey @BorjaLagarejo. You've sorted almost everything. The docs provide the details already https://github.com/udayvunnam/xng-breadcrumb/blob/main/docs/advanced-patterns.md#add-icons-in-front-of-label. Perhaps I should improve the documentation(PRs welcome 👍🏼 ) 

Fix: 

- xng-breadcrumb has a fixed name for passing additional context and that is **info** within the breadcrumb
- info has **any** type so can pass object/boolean/string

See the sample usage - https://github.com/udayvunnam/xng-breadcrumb/blob/c7ce2d0304c03ff65fb664b0a315ebfb88f99849/apps/breadcrumb-demo/src/app/app.component.html#L41
